const MARIAGE = {
  prenom1: "Léa",        nom1: "Bernard",
  prenom2: "Antoine",    nom2: "Rousseau",
  date_affichage: "Samedi 14 Juin 2025",
  date_iso:       "2025-06-14T15:00:00",
  rsvp_deadline:  "1er Avril 2025",
  domaine:        "Domaine de la Forêt Verte",
  ville:          "Fontainebleau, Seine-et-Marne",
  email:          "lea.antoine@exemple.com",
  whatsapp:       "06 11 22 33 44",
  langues:        ["fr"],
  photo_couple:   "photo-couple.png",
  photo_couple_caption: "Léa & Antoine · Forêt de Fontainebleau",
  hero_intro:     "Vous êtes conviés au mariage champêtre de",
  hero_cta:       "Confirmer ma présence",
  scroll_label:   "Découvrir",
  citation:       "« La nature est le plus beau des décors. »",
  histoire_eyebrow: "Depuis 2020",
  histoire_titre:   "Notre Histoire",
  histoire: [
    { annee: "2020", titre: "La Rencontre", texte: "Un week-end à vélo en forêt de Fontainebleau. Léa avait une crevaison, Antoine avait une pompe. Le reste appartient à l'histoire.", align: "left" },
    { annee: "2022", titre: "Le Voyage", texte: "La Provence en camping. Lavandes, cigales et couchers de soleil dorés. On a su que c'était pour la vie.", align: "right" },
    { annee: "2024", titre: "La Demande", texte: "Dans le jardin de la grand-mère de Léa, au milieu des roses trémières, Antoine a posé la question. Oui, mille fois oui.", align: "left" },
    { annee: "2025", titre: "Le Grand Jour", texte: "Entourés de nos proches, au cœur de la nature que nous aimons tant.", align: "right" },
    { annee: "", titre: "", texte: "", align: "left" },
  ],
  programme_eyebrow: "14 Juin 2025",
  programme_titre:   "Le Jour J",
  programme: [
    { heure: "15h00", icon: "🌿", titre: "Cérémonie en plein air",  lieu: "Prairie du domaine" },
    { heure: "16h30", icon: "🍾", titre: "Cocktail champêtre",      lieu: "Verger du domaine" },
    { heure: "20h00", icon: "🍽️", titre: "Dîner sous les étoiles",  lieu: "Grande Grange" },
    { heure: "23h00", icon: "🎶", titre: "Bal champêtre",            lieu: "Piste en bois" },
  ],
  galerie_eyebrow: "Notre havre de paix",
  galerie_titre:   "Le Domaine",
  galerie_hint:    "",
  galerie: [
    { icon: "🌳", label: "La Prairie",   photo: null },
    { icon: "🏡", label: "La Grange",    photo: null },
    { icon: "🌸", label: "Le Verger",    photo: null },
    { icon: "🌿", label: "Les Jardins",  photo: null },
  ],
  lieux_eyebrow: "Où nous rejoindre",
  lieux_titre:   "Les Lieux",
  lieux: [
    { icon: "🌿", type: "Cérémonie & Réception", nom: "Domaine de la Forêt Verte", adresse: ["77300 Fontainebleau"], featured: true, badge: "Lieu unique", btn: { label: "Voir sur la carte", href: "#map" } },
    { icon: "🏨", type: "Hébergement conseillé", nom: "Hôtel de la Forêt ★★★", adresse: ["12 Rue des Pins", "77300 Fontainebleau"], featured: false, badge: "", btn: { label: "Plus d'infos", href: "#infos" } },
  ],
  carte: { lat: 48.4024, lng: 2.7019, zoom: 13, nom: "Domaine de la Forêt Verte", adresse: ["77300 Fontainebleau"], caption: "📍 Domaine de la Forêt Verte · Fontainebleau" },
  dress_eyebrow: "Pour l'occasion",
  dress_titre:   "Code Vestimentaire",
  dress_intro:   "Tenue champêtre élégante. Talons déconseillés (pelouse). Inspirez-vous des teintes naturelles !",
  dress_couleurs: [
    { nom: "Vert sauge",  hex: "#8FAF8A", eviter: false },
    { nom: "Beige lin",   hex: "#C9B99A", eviter: false },
    { nom: "Crème",       hex: "#F5F0E5", eviter: false },
    { nom: "Terracotta",  hex: "#C4714A", eviter: false },
    { nom: "Blanc pur",   hex: "#FFFFFF", eviter: true },
  ],
  infos_eyebrow: "Tout savoir",
  infos_titre:   "Infos Pratiques",
  infos: [
    { icon: "🚗", titre: "Parking",     texte: "Parking gratuit sur le domaine. Depuis Paris : A6 sortie Fontainebleau." },
    { icon: "🚂", titre: "Train",       texte: "Gare de Fontainebleau à 5 km. Navettes organisées à 14h30." },
    { icon: "🏨", titre: "Hébergement", texte: "Chambres pré-réservées à l'Hôtel de la Forêt. Contactez-nous pour le code." },
    { icon: "👟", titre: "Chaussures",  texte: "La cérémonie se tient en plein air. Talons non recommandés." },
    { icon: "➕", titre: "", texte: "" },
  ],
  faq_titre: "Questions fréquentes",
  faq: [
    { q: "Peut-on venir avec des enfants ?", r: "Le domaine est accessible aux enfants. Un espace jeux sera aménagé." },
    { q: "Y a-t-il une liste de mariage ?",  r: "Oui, une cagnotte voyage et quelques idées sur notre site." },
    { q: "Comment nous contacter ?",         r: "Écrivez-nous à lea.antoine@exemple.com." },
    { q: "", r: "" },
  ],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "Confirmer votre présence",
  rsvp_intro: "Merci de nous répondre avant le 1er avril 2025.",
  photos_ambiance: [
    { src: null, position: "center" },
    { src: null, position: "center" },
    { src: null, position: "center" },
  ],
  activites: [
    { emoji: "🏸", titre: "Badminton",       description: "Raquettes disponibles sur place dans la prairie." },
    { emoji: "🎯", titre: "Pétanque",         description: "Terrain aménagé près du verger." },
    { emoji: "🚲", titre: "Balade à vélo",    description: "Vélos disponibles pour explorer les sentiers." },
    { emoji: "🌿", titre: "Atelier bouquets", description: "Créez votre bouquet de fleurs sauvages." },
  ],
  i18n: {},
};
