const MARIAGE = {
  prenom1: "Priya",      nom1: "Sharma",
  prenom2: "Arjun",      nom2: "Kapoor",
  date_affichage: "Samedi 14 Novembre 2026",
  date_iso:       "2026-11-14T16:00:00",
  rsvp_deadline:  "1er Septembre 2026",
  domaine:        "Château de Breteuil",
  ville:          "Choisel, Île-de-France",
  email:          "priya.arjun@exemple.com",
  whatsapp:       "06 33 55 77 99",
  langues:        ["fr"],
  photo_couple:   "priya-arjun-nowording.png",
  photo_couple_caption: "Priya & Arjun · Château de Breteuil",
  hero_intro:     "Vous êtes conviés à la célébration de",
  hero_cta:       "Rejoindre la fête",
  scroll_label:   "Découvrir",
  citation:       "« Deux âmes, deux cultures, une seule promesse. »",
  histoire_eyebrow: "Depuis 2022",
  histoire_titre:   "Notre Histoire",
  histoire: [
    { annee: "2022", titre: "La Rencontre", texte: "Un congrès international à Mumbai. Arjun cherchait sa salle de conférence, Priya avait le plan. Une conversation de cinq minutes qui a duré toute la nuit.", align: "left" },
    { annee: "2023", titre: "Paris, mon amour", texte: "Arjun rentre à Paris pour son poste. Priya prend l'avion quelques mois plus tard. La ville lumière devient leur terrain d'aventure commun.", align: "right" },
    { annee: "2025", titre: "Les Fiançailles", texte: "Dans les jardins du Château de Breteuil, sous les arbres centenaires, Arjun a posé la question avec une bague ornée d'un rubis. Priya a dit oui avant même qu'il termine sa phrase.", align: "left" },
    { annee: "2026", titre: "Le Grand Jour", texte: "Entourés de nos deux familles, de Mumbai à Paris, nous célébrons l'union de deux mondes.", align: "right" },
    { annee: "", titre: "", texte: "", align: "left" },
  ],
  programme_eyebrow: "14 Novembre 2026",
  programme_titre:   "Le Jour J",
  programme: [
    { heure: "14h00", icon: "✿", titre: "Cérémonie laïque",             lieu: "Grande Allée du Château" },
    { heure: "16h00", icon: "✿", titre: "Cocktail & Mehndi",             lieu: "Jardins du Château" },
    { heure: "19h30", icon: "✿", titre: "Dîner de fête",                 lieu: "Grande Orangerie" },
    { heure: "22h30", icon: "✿", titre: "Soirée Bollywood & Française",  lieu: "Toute la nuit !" },
  ],
  galerie_eyebrow: "Notre havre",
  galerie_titre:   "Le Domaine",
  galerie_hint:    "",
  galerie: [
    { icon: "🌿", label: "La Grande Allée", photo: null },
    { icon: "🏰", label: "Le Château",      photo: null },
    { icon: "🌸", label: "Les Jardins",     photo: null },
    { icon: "🍊", label: "L'Orangerie",     photo: null },
  ],
  lieux_eyebrow: "Où nous rejoindre",
  lieux_titre:   "Les Lieux",
  lieux: [
    { icon: "🌿", type: "Cérémonie & Réception", nom: "Château de Breteuil", adresse: ["78460 Choisel"], featured: true, badge: "Lieu unique", btn: { label: "Voir sur la carte", href: "#map" } },
    { icon: "🏨", type: "Hébergement conseillé", nom: "Auberge de l'Ill ★★★", adresse: ["12 Route de Chevreuse", "78460 Choisel"], featured: false, badge: "", btn: { label: "Plus d'infos", href: "#infos" } },
  ],
  carte: { lat: 48.6012, lng: 2.0402, zoom: 13, nom: "Château de Breteuil", adresse: ["78460 Choisel"], caption: "📍 Château de Breteuil · Choisel" },
  dress_eyebrow: "Pour l'occasion",
  dress_titre:   "Code Vestimentaire",
  dress_intro:   "Tenue élégante de fête. Inspirez-vous de notre palette : rouge, vert forêt, ivoire et or. Tenues traditionnelles indiennes bienvenues !",
  palette: [
    { nom: "Rouge sari",  hex: "#9B2335", eviter: false },
    { nom: "Vert forêt",  hex: "#1C3D2A", eviter: false },
    { nom: "Ivoire",      hex: "#FAF5EA", eviter: false },
    { nom: "Or",          hex: "#C9A557", eviter: false },
    { nom: "Blanc pur",   hex: "#FFFFFF", eviter: true },
  ],
  infos_eyebrow: "Tout savoir",
  infos_titre:   "Infos Pratiques",
  infos: [
    { icon: "🚗", titre: "Voiture",     texte: "Depuis Paris : N10 direction Chevreuse, 35 min. Parking gratuit dans le parc." },
    { icon: "🚂", titre: "Train",       texte: "RER B jusqu'à Saint-Rémy-lès-Chevreuse, puis navette à 13h30 et 15h30." },
    { icon: "🏨", titre: "Hébergement", texte: "Chambres pré-réservées à l'Auberge de l'Ill. Code : PRAK2026." },
    { icon: "✿",  titre: "Mehndi",      texte: "Un atelier mehndi (henné) sera proposé pendant le cocktail. Venez les mains prêtes !" },
    { icon: "➕", titre: "", texte: "" },
  ],
  faq_titre: "Questions fréquentes",
  faq: [
    { q: "Y a-t-il une liste de mariage ?",     r: "Oui, une cagnotte voyage et quelques idées. Détails après RSVP." },
    { q: "Les enfants sont-ils les bienvenus ?", r: "Absolument ! Un espace dédié sera aménagé pour les plus petits." },
    { q: "Comment nous contacter ?",             r: "Écrivez-nous à priya.arjun@exemple.com." },
    { q: "", r: "" },
  ],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "Confirmer votre présence",
  rsvp_intro: "Merci de nous répondre avant le 1er septembre 2026.",
  photos_ambiance: [
    { src: null, position: "center" },
    { src: null, position: "center" },
    { src: null, position: "center" },
  ],
  activites: [
    { emoji: "🪷", titre: "Atelier Mehndi",         description: "Faites-vous dessiner du henné par nos artistes lors du cocktail." },
    { emoji: "💃", titre: "Initiation Bollywood",    description: "Quelques pas de danse indienne pour mettre le feu à la piste !" },
    { emoji: "🌿", titre: "Balade dans les jardins", description: "Explorez les 80 hectares du parc classé du Château de Breteuil." },
    { emoji: "🎲", titre: "Jeux de société",         description: "Animations et jeux pour tous les âges." },
  ],
  hashtag: "#PriyaEtArjun2026",
  chanson: {
    titre:       "Tum Hi Ho",
    artiste:     "Arijit Singh",
    description: "La chanson qui jouait lors de notre premier regard à Mumbai. Elle sera notre première danse, entre les deux familles réunies.",
    spotify_url: "",
  },
  souhaits: [
    { emoji: "✈️", titre: "Voyage de noces au Rajasthan", description: "Contribuez à notre lune de miel dans les palais du Rajasthan.", lien: "" },
    { emoji: "🍛", titre: "Cours de cuisine indo-française", description: "Un cours de cuisine pour deux, entre épices indiennes et techniques françaises.", lien: "" },
    { emoji: "💐", titre: "Abonnement floral",              description: "Des fleurs fraîches livrées chaque mois dans notre nouvel appartement.", lien: "" },
    { emoji: "🎁", titre: "Enveloppe",                      description: "Toute contribution pour nous aider à construire notre nid sera précieuse.", lien: "" },
  ],
  mot_des_maries: "De Mumbai à Paris, deux familles, deux cultures, une seule promesse. Merci d'avoir traversé les kilomètres et les frontières pour être avec nous aujourd'hui. Ce mariage, c'est vous autant que nous. Avec tout notre amour — Priya & Arjun.",
  livre_or: { titre: "Livre d'Or", intro: "Laissez-nous un mot, il nous accompagnera toute notre vie.", actif: true },
  i18n: {},
};
