const MARIAGE = {
  prenom1: "Lucie",      nom1: "Martin",
  prenom2: "Thomas",     nom2: "Leclerc",
  date_affichage: "Dimanche 22 Juin 2025",
  date_iso:       "2025-06-22T16:00:00",
  rsvp_deadline:  "1er Avril 2025",
  domaine:        "Mas de la Garrigue",
  ville:          "Uzès, Gard",
  email:          "lucie.thomas@exemple.com",
  whatsapp:       "06 22 44 66 88",
  langues:        ["fr"],
  photo_couple:   "photo-couple.png",
  photo_couple_caption: "Lucie & Thomas · Garrigues provençales",
  hero_intro:     "Vous êtes conviés au mariage champêtre de",
  hero_cta:       "Confirmer ma présence",
  scroll_label:   "Découvrir",
  citation:       "« Là où fleurit la lavande, le bonheur aussi. »",
  histoire_eyebrow: "Depuis 2021",
  histoire_titre:   "Notre Histoire",
  histoire: [
    { annee: "2021", titre: "La Rencontre", texte: "Un week-end de randonnée en Ardèche. Lucie avait pris le mauvais sentier, Thomas avait la bonne carte. Une bonne raison de marcher ensemble.", align: "left" },
    { annee: "2023", titre: "La Provence", texte: "Un road trip en van à travers les champs de lavande du Lubéron. Les cigales, le rosé frais, le soleil couchant sur les Alpilles. On a su que c'était pour la vie.", align: "right" },
    { annee: "2024", titre: "La Demande", texte: "Dans le verger de la ferme familiale à Uzès, au milieu des lavandes en fleur, Thomas a posé la question avec un bouquet cueilli le matin même. Oui, mille fois oui.", align: "left" },
    { annee: "2025", titre: "Le Grand Jour", texte: "Entourés de ceux que nous aimons, au cœur de la Provence que nous chérissons tant.", align: "right" },
    { annee: "", titre: "", texte: "", align: "left" },
  ],
  programme_eyebrow: "22 Juin 2025",
  programme_titre:   "Le Jour J",
  programme: [
    { heure: "16h00", icon: "🌿", titre: "Cérémonie en plein air",       lieu: "Prairie du mas" },
    { heure: "17h30", icon: "🍾", titre: "Cocktail champêtre",            lieu: "Champ de lavande" },
    { heure: "20h00", icon: "🍽️", titre: "Dîner sous les étoiles",       lieu: "Grande Grange" },
    { heure: "23h00", icon: "🎶", titre: "Bal champêtre",                 lieu: "Piste en bois" },
  ],
  galerie_eyebrow: "Notre havre de paix",
  galerie_titre:   "Le Domaine",
  galerie_hint:    "",
  galerie: [
    { icon: "🌿", label: "La Prairie",         photo: null },
    { icon: "🏡", label: "La Grange",           photo: null },
    { icon: "💜", label: "Le Champ de Lavande", photo: null },
    { icon: "🌸", label: "Les Jardins",         photo: null },
  ],
  lieux_eyebrow: "Où nous rejoindre",
  lieux_titre:   "Les Lieux",
  lieux: [
    { icon: "🌿", type: "Cérémonie & Réception", nom: "Mas de la Garrigue", adresse: ["Route de Saint-Quentin-la-Poterie", "30700 Uzès"], featured: true, badge: "Lieu unique", btn: { label: "Voir sur la carte", href: "#map" } },
    { icon: "🏨", type: "Hébergement conseillé", nom: "Auberge des Vignes ★★★", adresse: ["8 Rue de la République", "30700 Uzès"], featured: false, badge: "", btn: { label: "Plus d'infos", href: "#infos" } },
  ],
  carte: { lat: 44.0111, lng: 4.4204, zoom: 13, nom: "Mas de la Garrigue", adresse: ["30700 Uzès"], caption: "📍 Mas de la Garrigue · Uzès" },
  dress_eyebrow: "Pour l'occasion",
  dress_titre:   "Code Vestimentaire",
  dress_intro:   "Tenue champêtre élégante. Talons déconseillés (pelouse et garrigue). Inspirez-vous des teintes provençales !",
  dress_couleurs: [
    { nom: "Lavande",    hex: "#9E91C0", eviter: false },
    { nom: "Sable",      hex: "#C9B496", eviter: false },
    { nom: "Ivoire",     hex: "#F0EAE0", eviter: false },
    { nom: "Vert thym",  hex: "#7A8C5A", eviter: false },
    { nom: "Blanc pur",  hex: "#FFFFFF", eviter: true },
  ],
  infos_eyebrow: "Tout savoir",
  infos_titre:   "Infos Pratiques",
  infos: [
    { icon: "🚗", titre: "Voiture",     texte: "Depuis Nîmes : 30 min via D979. Parking gratuit sur le domaine." },
    { icon: "🚂", titre: "Train",       texte: "Gare de Nîmes à 35 km. Navettes organisées depuis la gare à 15h00." },
    { icon: "🏨", titre: "Hébergement", texte: "Chambres pré-réservées à l'Auberge des Vignes à Uzès. Contactez-nous pour le code." },
    { icon: "👟", titre: "Chaussures",  texte: "La cérémonie se tient en plein air sur la garrigue. Talons non recommandés." },
    { icon: "➕", titre: "", texte: "" },
  ],
  faq_titre: "Questions fréquentes",
  faq: [
    { q: "Peut-on venir avec des enfants ?", r: "Le domaine est accessible aux enfants. Un espace jeux sera aménagé." },
    { q: "Y a-t-il une liste de mariage ?",  r: "Oui, une cagnotte voyage en Provence et quelques idées sur notre site." },
    { q: "Comment nous contacter ?",         r: "Écrivez-nous à lucie.thomas@exemple.com." },
    { q: "", r: "" },
  ],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "Confirmer votre présence",
  rsvp_intro: "Merci de nous répondre avant le 1er avril 2025.",
  photos_ambiance: [
    { src: null, position: "center" },
    { src: null, position: "center" },
    { src: null, position: "center" },
  ],
  activites: [
    { emoji: "🎯", titre: "Pétanque",                description: "Terrain aménagé à l'ombre des oliviers." },
    { emoji: "💜", titre: "Balade en lavande",        description: "Promenez-vous dans les champs de lavande du domaine." },
    { emoji: "🌿", titre: "Atelier bouquets",         description: "Créez votre bouquet provençal avec lavande et fleurs des champs." },
    { emoji: "🎲", titre: "Jeux en bois",             description: "Molkky, palets bretons et autres jeux de plein air." },
  ],
  i18n: {},
};
