const MARIAGE = {
  prenom1: "Camille",   nom1: "Fontaine",
  prenom2: "Édouard",   nom2: "de Villiers",
  date_affichage: "Vendredi 19 Septembre 2025",
  date_iso:       "2025-09-19T18:00:00",
  rsvp_deadline:  "1er Juillet 2025",
  domaine:        "Château de Valmont",
  ville:          "Paris, France",
  email:          "camille.edouard@exemple.com",
  whatsapp:       null,
  langues:        ["fr"],
  photo_couple:   null,
  photo_couple_caption: "",
  hero_intro:     "",
  hero_cta:       "RSVP",
  scroll_label:   "Défiler",
  citation:       "« L'élégance est le reflet de l'âme. »",
  histoire_eyebrow: "Depuis 2018",
  histoire_titre:   "Notre Histoire",
  histoire: [
    { annee: "2018", titre: "La Rencontre", texte: "Une soirée de gala à l'Opéra Garnier. Deux regards qui se croisent entre les colonnes de marbre.", align: "left" },
    { annee: "2021", titre: "Florence", texte: "Trois semaines en Toscane. Les galeries, les vignes, les dîners qui s'éternisent. Une certitude.", align: "right" },
    { annee: "2024", titre: "La Demande", texte: "Un dîner privé sur les toits de Paris. Une bague Art déco. Un oui susurré.", align: "left" },
    { annee: "2025", titre: "L'Union", texte: "Nous vous convions à célébrer notre mariage dans l'intimité et l'élégance.", align: "right" },
    { annee: "", titre: "", texte: "", align: "left" },
  ],
  programme_eyebrow: "XIX Septembre MMXXV",
  programme_titre:   "Le Programme",
  programme: [
    { heure: "18h00", icon: "I",   titre: "Cérémonie Laïque",  lieu: "Salon des Miroirs" },
    { heure: "19h30", icon: "II",  titre: "Cocktail",          lieu: "Terrasse panoramique" },
    { heure: "21h00", icon: "III", titre: "Dîner de Gala",     lieu: "Grande Salle" },
    { heure: "23h30", icon: "IV",  titre: "Soirée",            lieu: "Toute la nuit" },
  ],
  galerie_eyebrow: "",
  galerie_titre:   "",
  galerie:         [],
  photos: [
    { src: null, alt: "Le château" },
    { src: null, alt: "Le salon" },
    { src: null, alt: "La terrasse" },
    { src: null, alt: "Les jardins" },
    { src: null, alt: "La salle" },
    { src: null, alt: "Les détails" },
  ],
  lieux_eyebrow: "",
  lieux_titre:   "Le Lieu",
  lieux: [
    { icon: "◆", type: "Cérémonie & Réception", nom: "Château de Valmont", adresse: ["8 Avenue du Château", "75016 Paris"], featured: true, badge: "", btn: { label: "Carte", href: "#infos" } },
  ],
  carte: { lat: 48.8566, lng: 2.3522, zoom: 14, nom: "Château de Valmont", adresse: ["75016 Paris"], caption: "Château de Valmont · Paris" },
  dress_eyebrow: "",
  dress_titre:   "Dress Code",
  dress_intro:   "",
  dress_couleurs: [],
  infos_eyebrow: "",
  infos_titre:   "Informations",
  infos: [
    { icon: "◆", titre: "Accès",       texte: "Métro ligne 9 — station Ranelagh. Parking valet disponible." },
    { icon: "◆", titre: "Hébergement", texte: "Bloc de chambres réservées au Shangri-La Paris. Code : CMEV2025." },
    { icon: "◆", titre: "Contact",     texte: "camille.edouard@exemple.com" },
    { icon: "◆", titre: "", texte: "" },
  ],
  faq_titre: "",
  faq: [],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "R.S.V.P.",
  rsvp_intro: "Merci de confirmer votre présence avant le 1er juillet 2025.",
  photos_ambiance: [{ src: null }, { src: null }, { src: null }],
  dresscode: {
    texte: "Tenue de soirée exigée. Smoking ou costume sombre pour les messieurs. Robe longue ou tailleur élégant pour les dames.",
    couleurs: ["#F8F5EE", "#C9A96E", "#1A1A1A", "#8B7355", "#D4C5A9"],
  },
  i18n: {},
};
