const MARIAGE = {
  prenom1: "Aisha",    nom1: "Diallo",
  prenom2: "Marcus",   nom2: "Reed",
  date_affichage: "Samedi 18 Octobre 2025",
  date_iso:       "2025-10-18T18:00:00",
  rsvp_deadline:  "1er Août 2025",
  domaine:        "Villa Rothschild",
  ville:          "Cannes, Côte d'Azur",
  email:          "aisha.marcus@exemple.com",
  whatsapp:       null,
  langues:        ["fr"],
  photo_couple:   null,
  photo_couple_caption: "",
  hero_intro:     "",
  hero_cta:       "RSVP",
  scroll_label:   "Défiler",
  citation:       "« Ensemble est notre endroit préféré au monde. »",
  histoire_eyebrow: "Depuis 2019",
  histoire_titre:   "Notre Histoire",
  histoire: [
    { annee: "2019", titre: "La Rencontre", texte: "Une soirée jazz à Londres. Leurs regards se sont croisés par-dessus les verres de champagne. La conversation a duré jusqu'à l'aube.", align: "left" },
    { annee: "2022", titre: "New York", texte: "Marcus obtient un poste à Paris. Aisha le suit quelques mois plus tard. Une ville, deux destins, une seule direction.", align: "right" },
    { annee: "2024", titre: "La Demande", texte: "Un dîner privé face à la Méditerranée, à Nice. Une bague sertie de diamants. Un oui murmuré, les yeux dans les yeux.", align: "left" },
    { annee: "2025", titre: "L'Union", texte: "Nous vous convions à célébrer notre mariage dans l'élégance de la Côte d'Azur.", align: "right" },
    { annee: "", titre: "", texte: "", align: "left" },
  ],
  programme_eyebrow: "XVIII Octobre MMXXV",
  programme_titre:   "Le Programme",
  programme: [
    { heure: "18h00", icon: "I",   titre: "Cérémonie Laïque",         lieu: "Grand Salon" },
    { heure: "19h30", icon: "II",  titre: "Cocktail",                  lieu: "Terrasse méditerranéenne" },
    { heure: "21h00", icon: "III", titre: "Dîner de Gala",             lieu: "Grande Salle" },
    { heure: "23h30", icon: "IV",  titre: "Soirée",                    lieu: "Toute la nuit" },
  ],
  galerie_eyebrow: "",
  galerie_titre:   "",
  galerie:         [],
  photos: [
    { src: null, alt: "La villa" },
    { src: null, alt: "Le grand salon" },
    { src: null, alt: "La terrasse" },
    { src: null, alt: "Les jardins" },
    { src: null, alt: "La grande salle" },
    { src: null, alt: "Les détails" },
  ],
  lieux_eyebrow: "",
  lieux_titre:   "Le Lieu",
  lieux: [
    { icon: "◆", type: "Cérémonie & Réception", nom: "Villa Rothschild", adresse: ["7 Avenue Jean de Noailles", "06400 Cannes"], featured: true, badge: "", btn: { label: "Carte", href: "#infos" } },
  ],
  carte: { lat: 43.5528, lng: 7.0174, zoom: 14, nom: "Villa Rothschild", adresse: ["06400 Cannes"], caption: "Villa Rothschild · Cannes" },
  dress_eyebrow: "",
  dress_titre:   "Dress Code",
  dress_intro:   "",
  dress_couleurs: [],
  infos_eyebrow: "",
  infos_titre:   "Informations",
  infos: [
    { icon: "◆", titre: "Accès",       texte: "Gare de Cannes à 10 minutes en taxi. Service voiturier disponible à la villa." },
    { icon: "◆", titre: "Hébergement", texte: "Bloc de chambres réservées à l'Hôtel Martinez. Code : AMRD2025." },
    { icon: "◆", titre: "Contact",     texte: "aisha.marcus@exemple.com" },
    { icon: "◆", titre: "", texte: "" },
  ],
  faq_titre: "",
  faq: [],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "R.S.V.P.",
  rsvp_intro: "Merci de confirmer votre présence avant le 1er août 2025.",
  photos_ambiance: [{ src: null }, { src: null }, { src: null }],
  dresscode: {
    texte: "Tenue de soirée exigée. Smoking ou costume sombre pour les messieurs. Robe longue ou tailleur élégant pour les dames.",
    couleurs: ["#F8F5EE", "#C4956A", "#0A0A14", "#D4C5A9", "#8B7355"],
  },
  i18n: {},
};
