const MARIAGE = {
  prenom1: "Manon",     nom1: "Girard",
  prenom2: "Raphaël",   nom2: "Laurent",
  date_affichage: "Samedi 31 Mai 2025",
  date_iso:       "2025-05-31T15:30:00",
  rsvp_deadline:  "1er Mars 2025",
  domaine:        "Château des Roses",
  ville:          "Versailles, Île-de-France",
  email:          "manon.raphael@exemple.com",
  whatsapp:       "06 55 44 33 22",
  langues:        ["fr"],
  photo_couple:   "photo-couple.png",
  photo_couple_caption: "Manon & Raphaël · Jardins de Versailles",
  hero_intro:     "Avec tout notre amour, nous vous convions au mariage de",
  hero_cta:       "Confirmer ma présence",
  scroll_label:   "Découvrir",
  citation:       "« Aimer, c'est trouver sa richesse en l'autre. — Bossuet »",
  histoire_eyebrow: "Depuis 2019",
  histoire_titre:   "Notre Histoire d'Amour",
  histoire: [
    { annee: "2019", titre: "Le Coup de Foudre", texte: "Un soir de printemps lors d'un vernissage à Montmartre. Raphaël s'est approché avec un verre de rosé et un sourire timide. Le reste appartient à l'histoire.", align: "left", photo: null },
    { annee: "2022", titre: "Notre Voyage", texte: "La Grèce, l'été. Les îles Cyclades, le coucher de soleil depuis Santorin, la main dans la main. On a su que c'était pour toujours.", align: "right", photo: null },
    { annee: "2024", titre: "La Demande", texte: "Dans les jardins de Versailles, parmi les roses en fleur, Raphaël s'est agenouillé. Les larmes de joie de Manon ont dit oui avant ses mots.", align: "left", photo: null },
    { annee: "", titre: "", texte: "", align: "right", photo: null },
  ],
  programme_eyebrow: "31 Mai 2025",
  programme_titre:   "Notre Grand Jour",
  programme: [
    { heure: "15h30", icon: "♡", titre: "Cérémonie d'Union",    lieu: "Chapelle du Château" },
    { heure: "17h00", icon: "♡", titre: "Vin d'Honneur",        lieu: "Jardins en fleur" },
    { heure: "20h00", icon: "♡", titre: "Dîner de Fête",        lieu: "Grande Galerie" },
    { heure: "23h00", icon: "♡", titre: "Soirée Dansante",      lieu: "Toute la nuit !" },
  ],
  galerie_eyebrow: "",
  galerie_titre:   "",
  galerie:         [],
  photos: [
    { src: null, alt: "La chapelle" },
    { src: null, alt: "Les jardins" },
    { src: null, alt: "La grande galerie" },
    { src: null, alt: "Les roses" },
    { src: null, alt: "Le château" },
  ],
  lieux_eyebrow: "Où nous rejoindre",
  lieux_titre:   "Les Lieux",
  lieux: [
    { icon: "🌸", type: "Cérémonie & Réception", nom: "Château des Roses", adresse: ["12 Avenue des Roses", "78000 Versailles"], featured: true, badge: "Lieu unique", btn: { label: "Voir sur la carte", href: "#" } },
  ],
  carte: { lat: 48.8049, lng: 2.1203, zoom: 14, nom: "Château des Roses", adresse: ["78000 Versailles"], caption: "🌸 Château des Roses · Versailles" },
  dress_eyebrow: "",
  dress_titre:   "",
  dress_intro:   "",
  dress_couleurs: [],
  infos_eyebrow: "Tout ce qu'il faut savoir",
  infos_titre:   "Infos Pratiques",
  infos: [
    { icon: "🚗", titre: "Accès",        texte: "Depuis Paris : RER C direction Versailles-Rive-Gauche. Parking gratuit sur place." },
    { icon: "🏨", titre: "Hébergement",  texte: "Chambres réservées au Trianon Palace. Contactez-nous pour le code préférentiel." },
    { icon: "🌸", titre: "Tenue",        texte: "Tenue élégante souhaitée. Inspirez-vous de nos teintes roses et ivoire." },
    { icon: "➕", titre: "", texte: "" },
  ],
  faq_titre: "Questions fréquentes",
  faq: [
    { q: "Y a-t-il une liste de mariage ?", r: "Oui ! Une cagnotte voyage et quelques idées poétiques. Détails après RSVP." },
    { q: "Les enfants sont-ils bienvenus ?", r: "Nous accueillons les enfants avec joie. Un espace dédié sera aménagé." },
    { q: "", r: "" },
  ],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "Confirmer votre présence",
  rsvp_intro: "Votre présence est notre plus beau cadeau. Merci de nous répondre avant le 1er mars 2025.",
  photos_ambiance: [{ src: null }, { src: null }, { src: null }],
  // ── Champs spécifiques Romantique ──
  souhaits: [
    { emoji: "✈️", titre: "Voyage de noces", description: "Une contribution à notre lune de miel à Bali serait merveilleuse.", lien: "" },
    { emoji: "🌹", titre: "Un dîner romantique", description: "Offrez-nous une soirée inoubliable dans un beau restaurant parisien.", lien: "" },
    { emoji: "📚", titre: "Un beau livre", description: "Un livre illustré sur l'art, la nature, ou l'architecture.", lien: "" },
    { emoji: "🎁", titre: "Surprise", description: "Toute attention touchante et sincère nous ira droit au cœur.", lien: "" },
  ],
  mot_des_maries: "Merci d'être là pour partager ce moment magique avec nous. Votre présence transforme notre bonheur en quelque chose d'immense. Avec tout notre amour.",
  i18n: {},
};
