const MARIAGE = {
  prenom1: "Mei",       nom1: "Tanaka",
  prenom2: "Hiroshi",   nom2: "Yamamoto",
  date_affichage: "Samedi 12 Avril 2025",
  date_iso:       "2025-04-12T15:30:00",
  rsvp_deadline:  "15 Février 2025",
  domaine:        "Manoir des Cerisiers",
  ville:          "Giverny, Normandie",
  email:          "mei.hiroshi@exemple.com",
  whatsapp:       "06 78 90 12 34",
  langues:        ["fr"],
  photo_couple:   "photo-couple.png",
  photo_couple_caption: "Mei & Hiroshi · Jardins de Giverny",
  hero_intro:     "Avec tout notre amour, nous vous convions au mariage de",
  hero_cta:       "Confirmer ma présence",
  scroll_label:   "Découvrir",
  citation:       "« La fleur de cerisier est d'autant plus précieuse qu'elle est éphémère. »",
  histoire_eyebrow: "Depuis 2021",
  histoire_titre:   "Notre Histoire d'Amour",
  histoire: [
    { annee: "2021", titre: "Le Coup de Foudre", texte: "Un soir d'automne à Kyoto, lors d'une soirée d'échange culturel. Hiroshi s'est approché avec un thé au matcha et un sourire sincère. Le reste appartient à l'histoire.", align: "left", photo: null },
    { annee: "2023", titre: "Paris, Mon Amour", texte: "Mei débarque en France pour ses études. Hiroshi la rejoint quelques mois plus tard. Ensemble, ils découvrent les jardins de Giverny et comprennent qu'ils ont trouvé leur endroit préféré au monde.", align: "right", photo: null },
    { annee: "2024", titre: "La Demande", texte: "Sous les cerisiers en fleur du Manoir, alors que les pétales roses virevoltaient dans l'air, Hiroshi s'est agenouillé. Les larmes de Mei ont dit oui avant ses mots.", align: "left", photo: null },
    { annee: "", titre: "", texte: "", align: "right", photo: null },
  ],
  programme_eyebrow: "12 Avril 2025",
  programme_titre:   "Notre Grand Jour",
  programme: [
    { heure: "15h30", icon: "♡", titre: "Cérémonie d'Union",    lieu: "Chapelle du Manoir" },
    { heure: "17h00", icon: "♡", titre: "Vin d'Honneur",        lieu: "Jardin des Cerisiers" },
    { heure: "20h00", icon: "♡", titre: "Dîner de Fête",        lieu: "Grande Salle" },
    { heure: "23h00", icon: "♡", titre: "Soirée Dansante",      lieu: "Toute la nuit !" },
  ],
  galerie_eyebrow: "",
  galerie_titre:   "",
  galerie:         [],
  photos: [
    { src: null, alt: "La chapelle" },
    { src: null, alt: "Le jardin des cerisiers" },
    { src: null, alt: "La grande salle" },
    { src: null, alt: "Les cerisiers en fleur" },
    { src: null, alt: "Le manoir" },
  ],
  lieux_eyebrow: "Où nous rejoindre",
  lieux_titre:   "Les Lieux",
  lieux: [
    { icon: "🌸", type: "Cérémonie & Réception", nom: "Manoir des Cerisiers", adresse: ["2 Chemin du Clos Normand", "27620 Giverny"], featured: true, badge: "Lieu unique", btn: { label: "Voir sur la carte", href: "#" } },
  ],
  carte: { lat: 49.0763, lng: 1.5365, zoom: 14, nom: "Manoir des Cerisiers", adresse: ["27620 Giverny"], caption: "🌸 Manoir des Cerisiers · Giverny" },
  dress_eyebrow: "",
  dress_titre:   "",
  dress_intro:   "",
  palette: [],
  infos_eyebrow: "Tout ce qu'il faut savoir",
  infos_titre:   "Infos Pratiques",
  infos: [
    { icon: "🚂", titre: "Train",         texte: "Depuis Paris Saint-Lazare jusqu'à Vernon (1h), puis navette organisée à 14h45 depuis la gare." },
    { icon: "🏨", titre: "Hébergement",   texte: "Chambres réservées au Moulin de Giverny. Contactez-nous pour le code préférentiel." },
    { icon: "🌸", titre: "Tenue",         texte: "Tenue élégante souhaitée. Inspirez-vous de nos teintes cerisier et ivoire." },
    { icon: "➕", titre: "", texte: "" },
  ],
  faq_titre: "Questions fréquentes",
  faq: [
    { q: "Y a-t-il une liste de mariage ?", r: "Oui ! Une cagnotte voyage et quelques idées poétiques. Détails après RSVP." },
    { q: "Les enfants sont-ils bienvenus ?", r: "Nous accueillons les enfants avec joie. Un espace dédié sera aménagé." },
    { q: "", r: "" },
  ],
  video_hero: { type: "none", src: "" },
  rsvp_titre: "Confirmer votre présence",
  rsvp_intro: "Votre présence est notre plus beau cadeau. Merci de nous répondre avant le 15 février 2025.",
  photos_ambiance: [{ src: null }, { src: null }, { src: null }],
  hashtag: "",
  chanson: { titre: "", artiste: "", description: "", spotify_url: "" },
  activites: [],
  livre_or: { titre: "Livre d'Or", intro: "Laissez-nous un mot, il nous accompagnera toute notre vie.", actif: true },
  // ── Champs spécifiques Romantique ──
  souhaits: [
    { emoji: "✈️", titre: "Voyage de noces", description: "Une contribution à notre lune de miel au Japon serait merveilleuse.", lien: "" },
    { emoji: "🍽️", titre: "Une soirée gastronomique", description: "Offrez-nous une expérience culinaire dans un beau restaurant.", lien: "" },
    { emoji: "📸", titre: "Un livre de photos", description: "Un beau livre illustré sur la nature, l'art ou l'architecture japonaise.", lien: "" },
    { emoji: "🎁", titre: "Surprise", description: "Toute attention touchante et sincère nous ira droit au cœur.", lien: "" },
  ],
  mot_des_maries: "Merci d'être là pour partager ce moment magique avec nous. Votre présence transforme notre bonheur en quelque chose d'immense. Avec tout notre amour, Mei & Hiroshi.",
  i18n: {},
};
